02 Python/Tema 12 - Introducción a Django/ejercicio1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
]

urlpatterns += [
    path("", include("movies.urls")),
]

02 Python/Tema 12 - Introducción a Django/movies/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<pk>", views.DirectorView.as_view(), name="director_list"),
    path("movie/<pk>", views.MovieView.as_view(), name="movie_list"),
]

02 Python/Tema 12 - Introducción a Django/movies/models.py
from django.db import models
from django.urls import reverse

# Create your models here.


# Genre
class Genre(models.Model):
    name = models.CharField(
        max_length=200, help_text="Enter a movie genre (e.g. Fiction, Horror, etc.)"
    )

    def __str__(self):
        return self.name


# Language
class Language(models.Model):
    language = models.CharField(
        max_length=200,
        help_text="Enter movie language (e.g. English, Spanish, French, etc.)",
    )

    def __str__(self):
        return self.language


# Directors
class Director(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    biography = models.TextField()
    picture = models.URLField()
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField("Died", null=True, blank=True)

    def __str__(self):
        return "%s, %s" % (self.last_name, self.first_name)


# Movies
class Movie(models.Model):
    title = models.CharField(max_length=200)
    director = models.ForeignKey("Director", on_delete=models.CASCADE, null=True)
    plot = models.TextField()
    imdb = models.URLField(help_text="IMDB url")
    genre = models.ManyToManyField(Genre)
    language = models.ManyToManyField(Language)
    poster = models.URLField()
    year = models.PositiveIntegerField()
    duration = models.PositiveIntegerField(help_text="Movie duration in minutes")

    def duration_hours(self):

        hours = self.duration // 60
        minutes = self.duration % 60
        # Create time as a string
        time = "{}h {}m".format(hours, minutes)
        return time

    def __str__(self):
        return self.title

02 Python/Tema 12 - Introducción a Django/movies/views.py
# from django.shortcuts import render

from django.views import generic

from .models import Director, Movie


class IndexView(generic.ListView):
    template_name = "directors.html"
    model = Director


class DirectorView(generic.DetailView):
    template_name = "director.html"
    model = Director


class MovieView(generic.DetailView):
    template_name = "movie.html"
    model = Movie

02 Python/Tema 12 - Introducción a Django/movies/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>{% block title %}{% endblock %}</title>
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
		<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
	</head>
	<body>

		<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
			<div class="container">
				<a class="navbar-brand" href="/">
					<img src="{% static 'img/moviesdb.svg' %}" alt="" width="24" height="24" class="d-inline-block align-text-top">
					MoviesDB
				</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
    			</button>
				<div class="collapse navbar-collapse" id="navbarNav">
					<ul class="navbar-nav ms-auto">
						<li class="nav-item">
							<a class="nav-link" href="/">Home</a>
						</li>
					</ul>
				</div>
			</div>
		</nav>

		<div class="container pb-5">
			<header class="py-5">
				<h1 class="text-center">{% block header-title %}{% endblock %}</h1>
			</header>
			<main>{% block content %}{% endblock %}</main>
		</div>
		<footer class="bg-dark text-light d-flex justify-content-center align-items-center mt-5">
			<h4>
				<img src="{% static 'img/moviesdb.svg' %}" alt="" width="30" height="30" class="d-inline-block align-text-top me-1">
					MoviesDB
			</h4>
		</footer>
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
	</body>
</html>

02 Python/Tema 12 - Introducción a Django/movies/templates/director.html
{% extends "base.html" %}

{% block title %}{{director}}{% if director.date_of_death %}&dagger;{% endif %}{% endblock %}

{% block header-title %}{{director}}{% if director.date_of_death %}<sup>&dagger;</sup> {% endif %}{% endblock %}


{% block content %}

<div class="row">
	<div class="col-md-3">
		<div class="director-picture">
			<img src="{{ director.picture }}" alt="{{ director }}"><br>
		</div>
		<div class="meta py-2">
			<ul class="list-unstyled">
				<li><strong>Birth:</strong> {{director.date_of_birth}}</li>
				{% if director.date_of_death %}
				<li><strong>Died:</strong> {{director.date_of_death}} &dagger;</li>
				{% endif %}
			</ul>
			
		</div>
	</div>
	<div class="col-md-9">

		<nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
			<ol class="breadcrumb">
				<li class="breadcrumb-item"><a href="/">Home</a></li>
				<li class="breadcrumb-item active" aria-current="page">{{director}}</li>
			</ol>
		</nav>

		<h2 class="pb-3">Biography</h2>
		
		{{director.biography | linebreaks}}
	</div>
</div>

<div class="py-3">

</div>
<div class="row">
	<h2 class="pb-5 text-center">Películas</h2>
	{% for movie in director.movie_set.all %}
	<div class="col-md-4 col-lg-3 text-center">
		<a href="/movie/{{movie.id}}">
			<div class="movie-poster pb-5">
				<img src="{{ movie.poster }}" alt="{{ movie }}" class="img-fluid img-thumbnail"><br>
				<span>{{movie}}</span>
			</div>
			
		</a>
	</div>
	{% empty %}
		<div class="col-md-12">No hay peliculas aún</div>
	{% endfor %}
</div>

{% endblock %}

02 Python/Tema 12 - Introducción a Django/movies/templates/directors.html
{% extends "base.html" %}

{% block title %}Directors{% endblock %}

{% block header-title %}Directors{% endblock %}


{% block content %}

<div class="row">
    {% for director in object_list %}
        <div class="col-md-4 col-lg-3 text-center">
            <div class="director-picture pb-5">
                <a href="/{{director.id}}">
                    <img src="{{ director.picture }}" alt="{{ director }}" class="director-image"><br>
                    <h3 class="director-name py-2">{{ director }}{% if director.date_of_death %} &dagger;{% endif %}</h3>
                </a>
            </div>
        </div>
    {% empty %}
        <div class="col-md-12">
            <p>No hay directores</p>
        </div>

    {% endfor %}
</div>

{% endblock %}

02 Python/Tema 12 - Introducción a Django/movies/templates/movie.html
{% extends "base.html" %}

{% block title %}{{movie}} - {{movie.director}}{% endblock %}

{% block header-title %}{{movie}} <span>{{movie.year}} - {{movie.duration_hours}}</span>{% endblock %}


{% block content %}




<div class="row">

	<div class="col-md-3">
		<div class="movie-poster">
			<img src="{{ movie.poster }}" alt="{{ movie }}" class="img-thumbnail"><br>
		</div>
	</div>
	<div class="col-md-9">


		<nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
			<ol class="breadcrumb">
				<li class="breadcrumb-item"><a href="/">Home</a></li>
				<li class="breadcrumb-item"><a href="/{{movie.director.id}}">{{movie.director}}</a></li>
				<li class="breadcrumb-item active" aria-current="page">{{movie}}</li>
			</ol>
		</nav>
		
		<p class="lead">{{movie.plot}}</p>
		<table class="table">
			<tr>
				<td><strong>Director:</strong> <a href="/{{movie.director.id}}">{{movie.director}}</a></td>
			</tr>
			<tr>
				<td><strong>Year:</strong> {{movie.year}}</td>
			</tr>
			<tr>
				<td><strong>Duration:</strong> {{movie.duration_hours}}</td>
			</tr>
			<tr>
				<td><strong>Language:</strong> {{ movie.language.all|join:", " }}</td>
			</tr>
			<tr>
				<td><strong>Genre:</strong> {{ movie.genre.all|join:", " }}</td>
			</tr>
			<tr>
				<td><strong>IMDB:</strong> <a href="{{movie.imdb}}" target="_blank">{{movie.imdb}}</a></td>
			</tr>
		</table>

	</div>
		
	
</div>

{% endblock %}